import "./globals.css";

import type { Metadata } from "next";
import TanStackProvider from "@/components/TanStackProvider/TanStackProvider";
import Footer from "@/components/Footer/Footer";
import Header from "@/components/Header/Header";
import { Roboto } from "next/font/google";

const roboto = Roboto({
  subsets: ["latin"],
  weight: ["400", "700"],
  variable: "--font-roboto",
  display: "swap",
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
  icons: {
    icon: "/todo-icon.svg",
    shortcut: "/todo-icon.svg",
    apple: "/todo-icon.svg",
  },
};

export default function RootLayout({
  children,
  modal,
}: Readonly<{
  children: React.ReactNode;
  modal: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <TanStackProvider>
        <body className={`min-h-dvh flex flex-cd ${roboto.variable}`}>
          <Header />
          <main className="flex-1 page-content">{children}</main>
          {modal}
          <Footer />
        </body>
      </TanStackProvider>
    </html>
  );
}
